apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - react
    - nodejs
    - fullstack
    {% if values.database %}
    - ${{ values.database }}
    {% endif %}
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
  providesApis:
    - ${{ values.name }}-api
